ipfs/specs

records/README.md
https://github.com/ipfs/specs/issues/24#issuecomment-137188513
=> Signature is not part of the Record object itself

api/README.md, api/level1.md, api/level2/cli.md, api/level2/http.md
This is in reference to ipfs/api#11. Thanks @diasdavid for the suggestion.
=> Added the API Specs from ipfs/api

README.md
=> Added the three IPFS shields

README.md
=> Add note about PRs and issues

merkledag/ipld.md
Copy/Paste error made the design hard to follow.
Apologies for the ugly merge commit, was working quickly from the web interface.
=> Typo in traversal example

libp2p/8-implementations.md
I thought i'd take a stab at describing the rather complicated dialing logic in a spec
=> write down swarm dialing logic

ipld/README.md
This drove me nuts when I first read thru this spec, lol. I couldn't find the expansion anywhere else in the doc.
=> Expand the IPLD Abbreviation in first paragraph

overviews/modules.go
=> other typo

ipld/README.md
=> Remove link properties from CBOR tags as per #97

overviews/implement-api-bindings.md, overviews/implement-ipfs.md
This shouldn't change the meaning at all; it's just minor copy-editing tweaks.
=> Native English speaker fixes

overviews/implement-ipfs.md
Updated links to repos with libp2p implementations.
=> Fixed libp2p implementation links.

iprs-interplanetary-record-system/README.md
change formating to serializing in Record System definition for consistency.
=> match description identifiers

public-api/cli/README.md, public-api/core/README.md
Update for https://github.com/ipfs/go-ipfs/pull/5308
=> remove unwant from the public API

unixfs/README.md
Just the bits I need right now for the filecoin spec (we use unixfs as a transfer mechanism). If anyone wants to take this over from me and flesh out the rest of it, be my guest.
=> Add spec for file bits of unixfs v1

repo/README.md
In the context of the `Awesome Endeavour: Repo interoperability` [js-ipfs#1467](https://github.com/ipfs/js-ipfs/issues/1467), here is a PR updating the specs to the current state of the repo, as specified in the issue:
**Note:** I removed the `logs` part since it was cancelled a long time ago ([js-ipfs-repo#8](https://github.com/ipfs/js-ipfs-repo/issues/8)).
=> fix: update repo specs according to the current state of go-ipfs repo

UNIXFS.md
Addresses https://github.com/ipfs/specs/pull/236#issuecomment-571634058
It is a bit wordy, but I couldn't reduce it further. Also I *HOPE* there are fewer typos this time 🙀
=> Attempt to address mtime remnants of #236

IPNS.md
Fix missing parenthesis in markdown link
=> Fix missing parenthesis in IPNS.md

reframe/REFRAME_KNOWN_METHODS.md
Related: https://github.com/ipfs/go-delegated-routing/issues/55
=> Reframe: Add a note about limits on the number of keys per request.

ipns/IPNS.md
=> fix: ipns overview image url

http-gateways/PATH_GATEWAY.md
See https://github.com/ipfs/go-libipfs/issues/185
=> Return 500 on resolution errors

src/ipns/ipns-record.md
For preceeding discussion:
https://github.com/ipfs/specs/issues/406#issuecomment-1520901854
(and before that, Slack).
=> fix(ipns): use PascalCase for IpnsEntry.data (CBOR) fields

src/meta/spec-for-specs.md
I had updated the title information in 2cfedbce90dd0d167f0e288384e739d21f86797d, but then I noticed other things were missing!
=> Update Frontmatter Information

src/ipns/ipns-record.md
Cosmetic change that gives each field their own section (header and reusable definition)
=> chore: linkable ipns record field headers
