protocol/network/README.md, protocol/network/wire.md
this is also WIP but should be good enough to kick off node-ipfs and make the necessary changes to go-ipfs.
we do need to get the spdy situation figured out in go-ipfs or switch to something else. cc @whyrusleeping
=> added wire protocol description

modules/modules.go
Motivation for the two changes in their commit messages.
=> Adjust PublicKey.Verify API (take []bytes, only return error)

keychain/README.md
I believe the intended Key was the Public Key and not the Private Key used to sign
=> Change type of key in Signature to Public

merkledag/ipld.md
Child of PR #37 
Add precisions about the canonical format.
There was another solutions discussed: put a `@codec` key within the IPLD object when converting for instance a protocol buffer to JSON representation. There are problematic consequences:
- When receiving an object over the wire with the `@codec` key set to a format we know, we must decode and re-encode to this format to be sure that the hash is correct. Can be done.
- Makes it impossible to store JSON objects that have already a `@codec` key: we could document it as a limitation of the IPLD model
- We can't do anything with objects we receive that have a `@codec` key set to something we don't know.
It would be possible to escape the `@codec` key but:
- when getting the JSON representation of the IPLD object, the application must …
=> IPLD: precisions about canonical format

api/README.md, api/cli/README.md, api/core/README.md, api/http/README.md, api/level2/cli.md, api/level2/http.md
Upgraded the doc to reflect and indicate how we are organising our API specs. Moved from a `level` org to a `system` org (calling something level 1 and 2, when inside level 1 there are extensions and optional features made things a tad confusing).
Currently, the IPFS Core API (the programmatic interface) is still kind in flux (and that is ok), so no need to pressure ourselves into locking it down. The IPFS CLI happens as needed and as the system evolve. The only API spec that needs to get more stable, is the HTTP API as a lot of other libraries and applications depend on it.
Currently, the HTTP API is a mix of RPC and RESTful (it really isn't either), which makes it weird to assess. Having a RPC API gives us the chance of layering it over any other transport, while not having a RESTful …
=> WIP: IPFS API (core+http+cli)

merkledag/ipld.md
Merges to #37
Replaces `mlink` occurrences with `link` with a paragraph to explain how merkle-links are formed. [Original comment](/ipfs/specs/pull/37#discussion_r45558988) and [follow up](/ipfs/specs/pull/37#issuecomment-169775469)
=> Rename Merkle links key from mlink to link

merkledag/ipld.md
=> IPLD CBOR tagging

merkledag/ipld.md
Improves PR #37 and replaces PR #60. The idea is that there is only one kind of _merkle-paths_ that are not to be confused with unixfs paths. These paths are powerful enough to be able to access multiple properties in IPLD objects and resolve merkle links.
=> IPLD merkle-path improvements

merkledag/ipld-compat-protobuf.md, merkledag/ipld.md
This PR adds a new IPLD spec.
Some things TODO:
@mildred @diasdavid could you review?
=> WIP: IPLD spec

api/README.md, api/internals/README.md, api/internals/merkle-dag.md
Added reference to the internals API interface definitions. The purpose of this spec is to normalize interfaces (expectations) of each IPFS internal module, across all the language implementations. 
One of the results of creating this Internals API spec will be enabling other IPFS implementors to have a clear map of IPFS Architecture and digest each module, one at a time.
=> WIP: IPFS Internals API

merkledag/README.md
So they are actually clickable in https://github.com/ipfs/specs/tree/ipld-spec/merkledag
=> Use absolute link to github

libp2p/7-properties.md
Writing these down in the spec so that we agree and don't loose them again.
=> add multicodecs list to libp2p spec

ipld/README.md, ipld/ipld-compat-protobuf.md
This changes the spec to update the link fmt. Please review it carefully and suggest changes. This was a great simplification. thanks everyone.
See:
- https://github.com/ipfs/specs/issues/97
- https://github.com/ipfs/js-ipld/pull/17
=> update ipld spec with new link fmt

ipld/README.md
The QmV76pUdAAukxEHt9Wp2xwyTpiCmzJCvjnMxyQBreaUeKT object has no key "e".
Its only key that gives "e" is "c".
=> ipld/README: fix path example

ipld/README.md
Closing triple-backquotes were missing.
=> Fix small Markdown formatting bug in code sample.

README.md
I know this is here as a placeholder, but it is very confusing. See #113 and #120. If we want this to be a link, we should create an IPNS folder.
=> Remove dead link to IPNS

README.md, keychain/README.md, keystore/readme.md
In browsing the spec, noticed a broken link, as well as a few specs that didn't use badges to denote their status.
=> Use badges and fix link

README.md
=> Standardize README and add License

overviews/implement-ipfs.md
=> Fix links to repos

README.md
I have moved libp2p to github.com/libp2p/spec, keeping all of the commit history there. Some justification given in libp2p/website#8, but mostly this is clear; we have a libp2p organization, and the spec should be there, not in IPFS, now.
=> Move libp2p to libp2p/spec

README.md, public-api/cli/README.md, public-api/core/README.md
Stab at spec'ing out the CLI api of IPFS (//cc spec master @lgierth)
Notes:
- Formalization of the DAG API - https://github.com/ipfs/interface-ipfs-core/issues/81#issuecomment-277271941
- Expansion of the DAG API <@jbenet could you link here the hackpad we hacked at Ada's?>
- Interface-ipfs-core definition https://github.com/ipfs/interface-ipfs-core/tree/master/API/dag
=> feat/public-api/cli - dag-api

bitswap/README.md
This is a WIP, do not merge yet. It is just a placeholder while bitswap in js-ipfs gets implemented and I get a more in depth knowledge and ability of how to describe it.
=> WIP: bitswap spec

iprs-interplanetary-record-system/README.md
All the code treats it as a `time.Time` and that's the only thing that makes sense here.
I know it's just an example but good, correct examples help understanding the ideas and reasoning behind a spec.
=> change r.Expires from time.Duration to time.Time

repo/README.md, repo/fs-repo/README.md
The repo spec has some discrepancies to fix. I've added some commits that fix some, and noted others. This PR is a discussion to fix it.
Thanks to @masylum for prompting this fix, and sorry you had to find it by hand.
Discrepancies to address:
cc @ion1 @whyrusleeping @diasdavid
=> IPFS Repo Spec update

README.md
Some repos have moved from github.com/jbenet to github.com/multiformats
=> Update links to multiformats

architecture/README.md
["communcations => "communications"]. Line 95.
=> Fixed typo

dweb-addressing/README.md
This is a table of contents and intro for the addressing spec. (Some of this can surely be pulled out into a blog post or so later on.)
Please take a look and give some early feedback, I have a bunch more which isn't as coherent yet. A simple LGTM is sufficient too :)
cc @diasdavid @lidel @kyledrake @stebalien @whyrusleeping @Kubuxu @flyingzumwalt
=> Add DWeb Addressing intro and table of contents

bitswap/README.md
Editing and updating the Bitswap spec. Work in progress. Starts from https://github.com/ipfs/specs/pull/168
=> Bitswap spec update

unixfs/README.md
People get lost here when there’s no documentation and they don’t know about the `ipld-unixfs` repo, so I’ve replaced the empty specification with information about where current specification work is happening.
I’ve also updated the implementation section with links to the Go implementation. (@whyrusleeping are these the right links?)
(This is a follow-up to ipfs/unixfs-v2#8)
=> Clarify where work is going on in the UnixFS spec

merkledag/README.md
- Changed IPLD spec link just point to the IPLD specs repository rather than directly to the spec document, which has moved. We can either do this or point to a specific commit. Since I've been told the existing IPLD spec is not really stable/final, not pointing to a specific commit seemed better.
- Changed general specs link from relative to absolute. Relative links to branches (which is what you wind up with in this case) don't seem to work right on GitHub (they always get rendered as links to `<repo>/blob/<branch>` but it has to be `<repo>/tree/<branch>` to work, even though this is fine for files and subdirectories) :(
(Precipitated by #179)
=> Fix broken links in Merkle DAG spec & explain deprecation

public-api/README.md
The link to CLI public api specs was broken as the directory name is lower-case.
=> fix cli public api link

bitswap/README.md
Several aspects of Bitswap are out of date -- update to current understanding
- add Bitswap 1.1 fields
- update go repo (extracted out of IPFS)
=> docs(bitswap): update to current

UNIXFS.md
Following our Redux Redux meeting, here's what we decided (as I recall).  It largely swings back towards #220 with added sections on deduping and inlining and is more specific about the sizes of things.
The spec is updated with metadata implementation details and a decision rationale section has been added at the end.
Follows on from/supersedes #223
=> docs: adds spec sections for mode and mtime metadata

UNIXFS.md
Augment the mtime specification with a well-defined universal datastructure capable of expressing both arbitrarily distant points in time, and sufficiently arbitrary ( in computing terms ) sub-second precision. The very slight increase in on-wire size and the mild extra parsing complexity allows for:
- A structure representing time, that is unlikely to change any time in the future, aiding implementation convergence
- A way to encode any filesystem-related timestamp within the wider problem domain of information systems
=> Add timespec structured mtime metadata

naming/pubsub.md
IPNS over PubSub does not currently operate as an independent transport since it only receives updates, and has no way of getting existing published records. Additionally, even the current IPNS over PubSub does not have a spec.
This PR is meant to develop an IPNS over PubSub spec based on some of the ongoing work at ipfs/go-ipfs#6447.
This spec is also dependent on a libp2p spec for the Fetch protocol, which will be posted here as soon as a PR is up.
Please comment, make suggestions, and help make this spec better and easier to work with 😄
^ @hugomrdias @lidel would appreciate whether this spec looks complete enough that you wouldn't have to look at the Go code to implement this in JS.
=> IPNS-over-PubSub as an Independent Transport

KEYSTORE.md, REPO.md, REPO_FS.md
This makes the parts that have been implemented from the keystore spec be
reflected on the spec the way that they actually work. Focuses on:
* How keys are named and stored on disk (REPO_FS)
* What the current interface is (KEYSTORE)
=> Keystore: bring keystore spec more up to date

REFRAME.md
This is a proposal for an extensible protocol that we can use for endeavors such as delegated routing.
A few things to note for people less familiar with this project
1. Ask questions 😄, ideally the spec background can properly motivate its existence and how it works so we should fill in the blanks if things are missing
2. It is expected that this protocol will be in flux until we have some example client + server implementations operational, as is generally the case when trying to get feedback on protocols before they're already running in production and it's too late to change them
3. It is expected for this protocol to evolve to encapsulate more methods and use cases. Some glaringly obvious omissions for even covering the base cases of a delegated routing protocol are: Lack of methods …
=> Spec proposal for Reframe

REFRAME.md
I think the content-type in the REFRAME API spec should not be viewed as a part of the specific REFRAME API, but rather as a part of the RPC networking framework that the REFRAME API uses. I.e. there may be other APIs that use the same networking RPC stack. Consequently, the content-type should identify the networking framework itself rather than make a reference to the reframe API. So I am proposing we rename it from `application/vnd.ipfs.reframe+dag-json; version=1` to `application/vnd.ipfs.http+dag-json; version=1`.
=> generalize content-type in reframe spec

reframe/README.md, reframe/REFRAME_HTTP_TRANSPORT.md, reframe/REFRAME_KNOWN_METHODS.md, reframe/REFRAME_PROTOCOL.md
This PR decouples Transports and Known Methods from the generic RPC protocol and moves everything under `./reframe` directory, as proposed in https://github.com/ipfs/specs/pull/287#pullrequestreview-1013620192
Filled as PR against that PR for easier review (same content, different presentation).
(cc @aschmahmann @petar @willscott)
We don't have to, but it will make things easier to navigate going forward:
It allows us to add/modify methods and transports without  touching the protocol itself.
Rendered Markdown: https://github.com/ipfs/specs/tree/refactor/split-reframe-specs/reframe
=> refactor: split reframe specs

.github/CODEOWNERS, README.md, http-gateways/DNSLINK_GATEWAY.md, http-gateways/PATH_GATEWAY.md, http-gateways/README.md, http-gateways/SUBDOMAIN_GATEWAY.md, http-gateways/TRUSTLESS_GATEWAY.md
This PR adds initial HTTP gateway specs under `./http-gateways` directory. 
- https://github.com/ipfs/specs/blob/feat/gateway-specs/http-gateways/README.md
- most of the content is in https://github.com/ipfs/specs/blob/feat/gateway-specs/http-gateways/PATH_GATEWAY.md
The goal of this work is to document the _current_ behavior (based on implementation in [go-ipfs 0.13-rc1](https://github.com/ipfs/go-ipfs/releases/tag/v0.13.0-rc1)).
This is  a prerequisite that will allow us to **switch future gateway improvements to be specs-driven**:
- IPFS stewards and community members will be able to propose improvements as a diff against the specs
- See the plan to introduce [lightweight RFC process](https://github.com/ipfs/specs/issues/286)
- Different implementations will be able to adopt changes …
=> Add HTTP Gateway Specs

http-gateways/PATH_GATEWAY.md
> I remember discussing this with some gateway operators, but forgot to fix this before #283  got merged. 
This PR removes special-casing of CAR responses, 
and makes them  follow the same [`Cache-Control` rules](https://github.com/ipfs/specs/blob/main/http-gateways/PATH_GATEWAY.md#cache-control-response-header) as raw blocks and regular files:
> - `Cache-Control: public, max-age=29030400, immutable` must be returned for 
>  every immutable resource under `/ipfs/` namespace.
> - `Cache-Control: public, max-age=<ttl>` should be returned for mutable
>   resources under `/ipns/{id-with-ttl}/`
This fix already landed in https://github.com/ipfs/go-ipfs/pull/9080 and will be released in kubo 0.14-rc1.
The initial draft used `Cache-Control: no-cache, no-transform` for CARs as a precaution, as …
=> gateway: use regular cache-control for CARs

REFRAME.md, reframe/README.md, reframe/REFRAME_HTTP_TRANSPORT.md, reframe/REFRAME_KNOWN_METHODS.md, reframe/REFRAME_PROTOCOL.md
> Closes https://github.com/ipfs/specs/issues/282
Surgical spec tweak that aims to resolve caching problems described in https://github.com/ipfs/specs/issues/282, by providing both GET and POST endpoints (similar to json-rpc) 
- adding `GET /reframe/{mbase64url-dag-cbor}` endpoint for use cases where being able to leverage HTTP caching provides significant value
- adding _HTTP Caching Considerations_ section with
- POST vs GET explainer
- `Etag` for avoiding sending same response twice
- `Last-Modified` as a mechanism for clients to force response freshness 
lmk if this would do
@aschmahmann @guseggert  @willscott @thattommyhall @masih – this is by no means "final" – opened this PR to get the conversation started, looking for  an acceptable solution.
- probably better to skip - in most …
=> reframe: cacheable GET endpoint for HTTP transport

reframe/REFRAME_KNOWN_METHODS.md
Make the linter happy so https://github.com/ipfs/specs/pull/285 will pass once rebased. Also, modified some of the json responses to look like valid JSON.
=> chore: lint cleanup of reframe known methods

BITSWAP.md
The current Bitswap spec is a bit unwieldly and out of date and generally seemed in need of some cleaning up. The spec here was a rewrite but some notable changes include:
- Added `/ipfs/bitswap/1.2.0`
- Clarified the protocol identifiers used to identify the protocol versions
- Clarified the specified protocol message format per-protocol version
- Specified the maximum message size (4MiB)
- Specified the minimum compliant maximum block size (2MiB)
- Specified that messages are varint-delimited protobufs
=> Bitswap 1.2.0

naming/pubsub.md
Link in last line (line 94) is broken. I couldn't find which one it was supposed to be redirected to.
=> fix: links in  naming/pubsub.md

reframe/REFRAME_KNOWN_METHODS.md
* functionally, change `Key` from a single CID to an array of CIDs, to support extension to a `ProvideMany` case.
* update the example message to reflect current implementation in go-delegated-routing
=> update the reframe provide proposed spec

.github/workflows/linter.yml, .markdownlint.json, Makefile
small quality of life improvements
=> chore: improve markdown lint

reframe/REFRAME_HTTP_TRANSPORT.md
This PR is a small fix that aligns Reframe specs with existing Implementation.
[Percent-encoded](https://en.wikipedia.org/wiki/Percent-encoding) DAG-JSON sent over `?q=`  is what Kubo 0.16.0-rc1 uses,  and what is implemented in https://github.com/ipfs/go-delegated-routing v0.6.0.
I decided to add this to the spec, because it saves us time and does not block Kubo/Indexer work (we don't need to change the wire format).
It is a safe path: makes the spec both **backward-compatible** (with Kubo and go-delegated-routing) and **forward-compatible** (with proper CBOR support proposed in separate IPIP from https://github.com/ipfs/specs/pull/327).
cc @guseggert @petar @willscott
=> fix: document GET /reframe?q=

IPNS.md, README.md, ipns/IPNS.md, ipns/IPNS_PUBSUB.md, ipns/README.md
> Closes #314
This PR aims to document implementable IPNS Record creation and validation.
I've documented IPNS record creation and verification based on what latest Kubo and JS-IPFS do, but without v1 signatures  (as we want to remove support for them anyway).
Would appreciate additional :eye: from implementers and people working with IPNS.
- it is MUST, we also  have RSA which is 'SHOULD'
- yes, go-ipns uses dag-cbor from https://github.com/ipld/go-ipld-prime  internally
- yes, this is legacy which we want to go away (only relevant to Kubo and JS-IPFS)
- yes, for now we need to keep requirement of duplicated values – see rational in https://github.com/ipfs/go-ipns/pull/42
cc @2color @mrodriguez3313 @TMoMoreau @rvagg @vasco-santos
=> feat: update IPNS specification

IPIP/0001-lightweight-improvement-proposal-process.md, IPIP_PROCESS.md, README.md
Proposing some restructuring, rewording, and more structured consensus protocol for moving proposals through the process
=> Proposed v2 of the IPIP process

routing/DELEGATED_CONTENT_ROUTING_HTTP.md
Reduce the scope of IPIP-337 by temporarily excluding write operation. The write operations are to be added in a separate PR once the IPIP-337 is merged.
See:
- https://github.com/ipfs/specs/pull/337
=> Reduce the scope of IPIP-337 by excluding write operations

ARCHITECTURE.md, IMPORTERS_EXPORTERS.md, IPIP/0001-lightweight-improvement-proposal-process.md, IPIP_PROCESS.md, KEYSTORE.md, MERKLE_DAG.md, REPO_FS.md, http-gateways/PATH_GATEWAY.md, http-gateways/REDIRECTS_FILE.md, http-gateways/SUBDOMAIN_GATEWAY.md, ipns/IPNS.md
Bulk edit for spelling. List of changes by page is below:
ARCHITECTURE.md
- All instances of "datastructure" / "datastructures" -> "data structure" / "data structures"
- System -> System, line 106
- apriori -> a priori, line 122
IMPORTERS_EXPORTERS.md
- All instances of "datastructure" / "datastructures" -> "data structure" / "data structures"
- All instances of "eg" -> "e.g." _(I realize this might be an English dialect thing, just suggesting the American English version because it's commonly used)_
IPIP/0001-lightweight-improvement-proposal-process.md
- Github -> GitHub, line 106
IPIP_PROCESS.md
- Github -> GitHub, line 78
- intial -> initial, line 88
KEYSTORE.md
- acommodate -> accommodate
MERKLE_DAG.md
- All instances of "datastructure" / "datastructures" -> "data structure" / "data …
=> docs: Bulk spelling edits

ipns/IPNS.md
afaict ‘IpfsEntry’ (with the ‘f’) is ambiguous, as it appears nowhere else in the document. This was probably a typo?
😅
=> fix typo in IPNS.md ‘IpfsEntry’ -> ‘IpnsEntry’

http-gateways/PATH_GATEWAY.md
See https://github.com/ipfs/go-libipfs/pull/205
=> docs: return 400 Bad Request on Invalid CIDs

src/architecture/index.html, src/architecture/principles.md, src/index.html
This is the PR for the [IPFS Principles](https://hackmd.io/tkHHmdTfTZatyY-35PGVhA?both) draft we have been working on. I'm keeping it as a draft pending further feedback and also because it needs the site to land before it can land.
I hesitated but I didn't file an IPIP with this on the grounds that it doesn't add or modify any implementation. That being said these considerations are potentially load-bearing and this document might end up being referred to a fair bit, so I'm happy to add an IPIP if others prefer it that way!
=> IPFS Principles

src/_includes/specs/architecture.html, src/architecture/index.html, src/index.html
I'll merge this if CI passes. This is a minor fix and should've been done in the PR where this was added.
=> fix: keep architecture listing in sync

src/index.html
I did this because it seems a bit odd to have underlying elements like architecture and meta at the bottom even though they are foundational for the specs that follow.
This was flagged to me in a side comment by @momack2 .
=> Put architecture/meta up top

src/http-gateways/path-gateway.md, src/http-gateways/trustless-gateway.md, src/ipips/ipip-0351.md
=> IPIP-351: IPNS Signed Records Response Format on HTTP Gateways 

Makefile
Fixes a small bug I inadvertently added to the spec-generator: when the spec would start with a title, it would be considered part of the abstract. This affected IPIPs. It is now fixed.
=> feat: bump spec-generator version

README.md
- Fixes: [Issue-363](https://github.com/ipfs/specs/issues/363)
- Removed the `IPFS Overviews` broken link.
- Added `IPFS Guide` which redirects users to [here](https://docs.ipfs.tech/).
=> fix: remove broken link and update README

src/ipips/ipip-0410.md, src/routing/http-routing-v1.md
Closes #344. Based on #379.
- https://github.com/ipfs/kubo/pull/9868
- https://github.com/ipfs/kubo/pull/9874
=> IPIP-410: Streaming Routing V1 HTTP API

src/http-gateways/dnslink-gateway.md, src/http-gateways/path-gateway.md, src/http-gateways/subdomain-gateway.md, src/http-gateways/trustless-gateway.md, src/http-gateways/web-redirects-file.md, src/ipns/ipns-record.md
This editorial PR: replaces ambiguous 'free to' with SHOULD/MAY
=> style: 'free to' → SHOULD/MAY

src/http-gateways/path-gateway.md
See https://github.com/ipfs/boxo/pull/369.
=> path-gateway: clarify Range should support single range

src/http-gateways/path-gateway.md
This is a cosmetic change to Gateway spec that 
- adds missing HTTP 502
- this is used in projects like Saturn/Rhea for indicating content routing error for requested content path (making it distinct from 504 which is timeout during retrieval phase)
- adds missing guidance around `Retry-After` header, which should be leveraged for throttling (429) and in 502 and 504
(We don't need IPIP as this is filling a gap in existing specs to describe production behavior, not adding/changing anything new.)
=> gateway: document Retry-After header

src/ipips/ipip-0428.md, src/ipns/ipns-record.md
Closes https://github.com/ipfs/specs/issues/376
This IPIP introduces support for creation and validation of compact, V2-only IPNS Records.
- done: https://github.com/ipfs/boxo/pull/339
=> IPIP-428: Allowing V2-Only Records in IPNS

src/http-gateways/path-gateway.md
See https://github.com/ipfs/boxo/pull/459#pullrequestreview-1609790478. This is more of a clarification/cleanup and therefore requires no IPIP.
=> gateway: clean Cache-Control and Last-Modified

src/ipips/ipip-0417.md, src/routing/http-routing-v1.md
This IPIP introduces the `/routing/v1/peers` endpoint to the Routing HTTP V1 API for peer routing support.
=> IPIP-417: Delegated Peer Routing HTTP API

src/ipns/ipns-record.md
Initial context: https://github.com/ipfs/interface-go-ipfs-core/pull/94#discussion_r1085244474.
Currently, the default IPNS Entry TTL is hard coded to 1 minute. 1 minute is a very short duration for TTL. For DNS, 12 and 24 hours are very common TTL values. If we have a low value from the start, there is barely any performance improvement by setting a TTL manually, since no one is going to manually set it for a larger value.
With this PR, we would like to add a suggested default of 12 hours. If the user (publisher of the website), requires more frequent updates, they can always use the `--ttl` flag in `ipns name publish` to override the default.
=> Document suggested IPNS Entry TTL default

src/http-gateways/libp2p-gateway.md
closes #433 
Recommendations on wording and if more examples/specifics from the current draft of libp2p+http spec PR (https://github.com/libp2p/specs/pull/508) are desired are welcome.
Overall, this PR is just specifying that the protocol ID to use for the Gateway API is `/ipfs/gateway`
=> feat(gateway): add specification for running the gateway over libp2p

src/http-gateways/dnslink-gateway.md, src/http-gateways/libp2p-gateway.md, src/http-gateways/path-gateway.md, src/http-gateways/subdomain-gateway.md, src/http-gateways/trustless-gateway.md, src/http-gateways/web-redirects-file.md
This PR does not change specs, just cleans up the metadata (adds affinity and improves descriptions).
cc @autonome @darobin @2color @ElPaisano @BigLep @hacdias   for additional eyeballs
Goal is to make it easier to reason about  HTTP-related items listed on  https://specs.ipfs.tech landing page.
=> chore: missing affinity and improved descriptions

src/http-gateways/path-gateway.md
Closes #458 cc @SgtPooki 
This was not specified, but `Accept` takes precedence.
The `format` parameter is provided as UX courtesy, mostly used for creating shareable links and download links on websites. `Accept` overrides it, as the content type may have parameters which can only be passed via HTTP header (e.g. [`order` of CAR](https://specs.ipfs.tech/http-gateways/trustless-gateway/#car-order-content-type-parameter))
=> gateway: clarify format negotiation precedence

src/http-gateways/path-gateway.md
Clarification prompted by discussion in https://github.com/ipfs-shipyard/helia-service-worker-gateway/issues/62 as it felt the reason we do this was not clear enough. 
Suggestions on wording/examples appreciated.
=> gateway: explain why we normalize to trailing slash in dir URLs

src/routing/http-routing-v1.md
Request from https://github.com/ipfs/boxo/pull/584/.
=> /routing/v1: add missing HTTP cache headers

src/http-gateways/path-gateway.md, src/http-gateways/trustless-gateway.md
Document `Content-Location` as part of the work in https://github.com/ipfs/boxo/pull/603.
Context: https://github.com/ipfs/boxo/issues/606
=> gateways: document Content-Location

src/http-gateways/libp2p-gateway.md
Renaming resource to follow latest libp2p spec draft and go-libp2p:
https://github.com/libp2p/specs/pull/508#discussion_r1550303385 https://github.com/libp2p/specs/pull/508/commits/3c0ac4033dd640425e047ee448771dbca244ba68 https://github.com/libp2p/go-libp2p/pull/2757
=> libp2p-gateway: .well-known/libp2p/protocols

src/http-gateways/path-gateway.md, src/http-gateways/trustless-gateway.md
We already had this interop note in `format` section, this makes it more prominent and also present in `Accept`. 
cc @aschmahmann
=> chore: format/accept SHOULD note more prominent

src/compact-denylist-format.md
This PR adds a short mention how legacy doublehash notation can be used for representing IPNS and DNSLink block rules.
What prompted me to adding this to specs is the fact that IPNS entries (double-hashed CIDv1 with libp2p-key codec) already are on https://badbits.dwebops.pub/ and we also have cases where a very bad ENS DNSLink needs to be blocked for legal reasons. 
No IPIP because it does not change spec, only clarifies how to use existing notation in mutable context, which was missing from the spec.
Ref. internal issues with additional context (sadly too sensitive, can't be public):
- https://github.com/ipshipyard/waterworks-infra/issues/209
- https://github.com/protocol/badbits.dwebops.pub/pull/40002
=> denylists: clarify doublehash way of supporting IPNS

src/compact-denylist-format.md
I was reading through this spec and noticed a slight grammatical error. read through the rest and didn't spot anything
=> chore: grammatical fix in compact-denylist-format

src/routing/http-routing-v1.md
Clarify that the delegated routing peer routing endpoint accepts both CID and Multihash encoded PeerIDs
=> chore: clarify accepted Peer IDs

src/ipns/ipns-record.md
Adjusting the suggested default due to the rationale from https://github.com/ipfs/kubo/issues/10718
Reference implementation changes:
- `boxo/ipfs.DefaultRecordTTL`: https://github.com/ipfs/boxo/pull/859
- `@helia/ipns`: https://github.com/ipfs/helia/pull/749
=> ipns: lower the suggested default TTL

.github/workflows/build.yml, .github/workflows/main.yml, .gitignore, Makefile, package-lock.json, package.json
Working towards simplified hosting like the one we did for https://ipns.ipfs.network (no Fleek, HTTPS handled by Github +  multiple independent IPFS mirrors and DNSLink).
cc @2color for visibility
- hangs, needs https://github.com/ipfs/ipfs-deploy-action/issues/22 
- keeping as-is for now
=> refactor(ci): local  build

src/http-gateways/libp2p-gateway.md
This PR updates `src/http-gateways/libp2p-gateway.md` to reflect latest status of ecosystem, including http retrieval (without libp2p),  content-type negotiation best practices and guidance on PeerID auth being optional for http-only retrieval
cc @aschmahmann @hsanjuan @2color
=> libp2p+http: clarify peerid auth optionality and gw type detection

src/http-gateways/subdomain-gateway.md
This PR aims to clarify Public Suffix List and eTLD best practices under existing security considerations section in notes for implementers.
It was already there, but easy to miss + did not mention what may happen of PSL entry is not present. 
cc @mishmosh @bumblefudge @darobin @2color for visibility / feedback – this was discussed at recent IPFS Protocol WG
=> subdomain gateway: clarify PSL and eTLD best practices
